# frozen_string_literal: true

#
# Generated by bristle. Changes outside the custom configuration section will be overwritten.
#
source "https://rubygems.org"

gemspec

# >>> Custom configuration
gem "coveralls", github: "jochenseeber/coveralls-ruby", tag: "v0.8.23-js"
# <<< Custom configuration
